✨ feat: welfare and typing refactor
RecruitRadar/RecruitRadar pull request #4
Opened 2023-08-09 10:15 UTC by HaJunYoo

## 변경 내용

- welfare 칼럼 추가
- typing hint 추가적

2023-08-09 11:16 UTC, heewoneha requested changes

2023-08-09 11:16 UTC, heewoneha commented on rallit_scraper/rallit_api.py
> +    main()
동작에 문제는 없지만 저번 멘토님께서도 [언급](https://greppkdt-hq.slack.com/archives/C052SSD3CBU/p1683205575420549)하신 내용이어서요!
EOF를 추가하면 좋을 것 같습니다. 👍

2023-08-09 13:06 UTC, HaJunYoo commented on rallit_scraper/rallit_api.py
> +    main()
EOF 라면 메인 함수 try ~ exeption 처리를 말씀해주시는 걸까요??

2023-08-09 13:43 UTC, heewoneha commented on rallit_scraper/rallit_api.py
> +    main()
python 파일의 맨 아래 줄 End Of File 입니다! [참고](https://hjuu.tistory.com/8)링크 남깁니다~

2023-08-10 11:01 UTC, heewoneha approved these changes

2023-08-10 11:02 UTC, merged